// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBckYwkje97oDk4p0ZTNK6w1gSOcOiPN7E',
    appId: '1:384053106480:android:6da436f9f571a4902fdaf5',
    messagingSenderId: '384053106480',
    projectId: 'flutterauth-2cb3e',
    storageBucket: 'flutterauth-2cb3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxuKTCaeVDl6NHFZdEvD0USlGO4G9BSY',
    appId: '1:384053106480:ios:6eb748482d21ccc82fdaf5',
    messagingSenderId: '384053106480',
    projectId: 'flutterauth-2cb3e',
    storageBucket: 'flutterauth-2cb3e.firebasestorage.app',
    iosClientId: '384053106480-koe7d5g566goik1utmnliubun92h2jq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.yaz',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCDYEkRez06Yc8oIwzR5fH81gOY2jslSc',
    appId: '1:384053106480:web:a594cb38eb974f6d2fdaf5',
    messagingSenderId: '384053106480',
    projectId: 'flutterauth-2cb3e',
    authDomain: 'flutterauth-2cb3e.firebaseapp.com',
    storageBucket: 'flutterauth-2cb3e.firebasestorage.app',
    measurementId: 'G-J5XGC9L584',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVxuKTCaeVDl6NHFZdEvD0USlGO4G9BSY',
    appId: '1:384053106480:ios:6eb748482d21ccc82fdaf5',
    messagingSenderId: '384053106480',
    projectId: 'flutterauth-2cb3e',
    storageBucket: 'flutterauth-2cb3e.firebasestorage.app',
    iosClientId: '384053106480-koe7d5g566goik1utmnliubun92h2jq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.yaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCDYEkRez06Yc8oIwzR5fH81gOY2jslSc',
    appId: '1:384053106480:web:25049491736e4baa2fdaf5',
    messagingSenderId: '384053106480',
    projectId: 'flutterauth-2cb3e',
    authDomain: 'flutterauth-2cb3e.firebaseapp.com',
    storageBucket: 'flutterauth-2cb3e.firebasestorage.app',
    measurementId: 'G-GZ6F7HQWRZ',
  );

}